/*
* generated by Xtext
*/
package tr.edu.metu.ceng.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class XperimenterAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("tr/edu/metu/ceng/parser/antlr/internal/InternalXperimenter.tokens");
	}
}
