/*
 * generated by Xtext 2.18.0
 */
package io.github.odayibas


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class XperimenterRuntimeModule extends AbstractXperimenterRuntimeModule {
}
