/*
* generated by Xtext
*/
package tr.edu.metu.ceng;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class XperimenterUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return tr.edu.metu.ceng.ui.internal.XperimenterActivator.getInstance().getInjector("tr.edu.metu.ceng.Xperimenter");
	}
	
}
