/*
 * generated by Xtext
 */
package tr.edu.metu.ceng.ui.contentassist

import tr.edu.metu.ceng.ui.contentassist.AbstractXperimenterProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class XperimenterProposalProvider extends AbstractXperimenterProposalProvider {
}
