/*
 * generated by Xtext 2.18.0
 */
package tr.edu.metu.ceng


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XperimenterStandaloneSetup extends XperimenterStandaloneSetupGenerated {

	def static void doSetup() {
		new XperimenterStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
