/*
 * generated by Xtext 2.18.0
 */
package tr.edu.metu.ceng.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class XperimenterWebModule extends AbstractXperimenterWebModule {
}
