/*
 * generated by Xtext
 */
package tr.edu.metu.ceng.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractXperimenterValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(tr.edu.metu.ceng.xperimenter.XperimenterPackage.eINSTANCE);
		return result;
	}
}
