/*
* generated by Xtext
*/
package tr.edu.metu.ceng;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XperimenterStandaloneSetup extends XperimenterStandaloneSetupGenerated{

	public static void doSetup() {
		new XperimenterStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

