/*
 * generated by Xtext
 */
package tr.edu.metu.ceng;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XperimenterRuntimeModule extends tr.edu.metu.ceng.AbstractXperimenterRuntimeModule {

}
