/*
 * generated by Xtext
 */
package tr.edu.metu.ceng.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XperimenterUiModule extends tr.edu.metu.ceng.ui.AbstractXperimenterUiModule {
	public XperimenterUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
