/*
 * generated by Xtext
 */
package tr.edu.metu.ceng.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import tr.edu.metu.ceng.ui.internal.XperimenterActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XperimenterExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XperimenterActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XperimenterActivator.getInstance().getInjector(XperimenterActivator.TR_EDU_METU_CENG_XPERIMENTER);
	}
	
}
